my_project:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5438
      user: postgres
      pass: pass
      dbname: store
      schema: public

  target: dev

